owlbot-postprocessor/README.md
owlbot-postprocessor/lib/owlbot.rb
owlbot-postprocessor/test/test_owlbot.rb

This fixes the odd behavior where changelog and version files initially show up as generated but later "move" to static.

fix!: Removed preserved paths and reimplemented changelog/version preservation using modifiers

---

toys/release/.data/rad-yard-templates/default/layout/yaml/method.rb
toys/release/.data/rad-yard-templates/default/layout/yaml/setup.rb

Two more fixes:
* Fixed a crash when a tag (such as `@yield`) omitted an expected type. This was blocking google-cloud-logging.
* Removed class variables spuriously included in YAML. This was blocking google-cloud-trace.

fix(rad): Several additional Cloud-RAD fixes

---

toys/release/.data/rad-yard-templates/default/layout/yaml/format.rb

Fixes some formatting bugs when rendering snippetgen samples with client-side streaming. (Those include sample code that uses the `<<` operator.)

fix(rad): Escape ampersands and angle brackets in code blocks

---

toys/release/.data/rad-yard-templates/default/fulldoc/yaml/setup.rb
toys/release/build-rad.rb

A few cloud-rad fixes:
* Prevent removal of the blank line between the first header and the rest of the content in a markdown file.
* Changelog headers now list the gem name
* Disable the yardopts file when invoking yard, to avoid confusing yard due to duplicated arguments
* Omit the license, code of conduct, and contributing markdown files from the output

fix(rad): Omit license, code of conduct, and contributing docs from output

---

owlbot-postprocessor/lib/owlbot.rb
owlbot-postprocessor/test/test_owlbot.rb

Update the owlbot postprocessor to preserve the `release_level` repo-metadata field. This field will be updated by other processes in the google-cloud-ruby repo, and we don't want owlbot reverting it.

feat(owlbot): Preserve release_level repo metadata field

---

toys/release/.data/rad-yard-templates/default/examples/class_example.yml
toys/release/.data/rad-yard-templates/default/layout/yaml/_constant.erb
toys/release/.data/rad-yard-templates/default/layout/yaml/_method.erb
toys/release/.data/rad-yard-templates/default/layout/yaml/_object.erb
toys/release/.data/rad-yard-templates/default/layout/yaml/_reference.erb
toys/release/build-rad.rb

This adds a new argument to the build-rad tool to accept the friendly API name of a gem. This is then added into the yard template for reference pages.

feat(release): Generate yaml with friendlyApiName key for reference docs

---

.toys/ci.rb
owlbot-postprocessor/lib/owlbot/common_modifiers.rb
owlbot-postprocessor/test/test_owlbot.rb

https://github.com/googleapis/google-cloud-ruby/pull/19265 notes that some generated Ruby clients have the wrong `library_type` in the `.repo-metadata.json`. This file is generated, but the correct value cannot be determined conclusively by the generator because it doesn't know whether there are partial gapics (which would distinguish between `GAPIC_AUTO` and `GAPIC_COMBO` types). So we push this logic into the OwlBot postprocessor, which does know (based on the owlbot manifest) whether there are handwritten partial gapic files in the library.

feat(owlbot): Analyze the library and set library_type in repo-metadata

---

toys/release/.data/rad-yard-templates/default/layout/yaml/method.rb
toys/release/build-rad.rb

* The `release build-rad` tool deletes the `doc` and `.yardoc` directories before executing yard, to ensure no leakage from earlier runs. This should prevent html files from normal yard runs from getting into docfx output for cloud-rad
* The `release build-rad` tool defaults yardopts to `.yardopts-cloudrad` if it exists.
* Fixed a rare crash in the cloud-rad template that appeared in the pubsub veneer.

fix(rad): Clean up before building rad, and fix a corner case crash

---

.github/workflows/ci.yml
.kokoro/trampoline_v2.sh
.toys/ci.rb
gas/.gitignore
gas/.toys/.toys.rb
gas/README.md

Initial files and preparation for Ruby Gems-As-a-Service. This is boilerplate that I'm splitting out into a separate commit for clarity.
Specifics:
* Update Ruby version used for CI, to 3.1, because the implementation uses Ruby 3.1 features.
* Add Trampoline V2 which is used for Ruby Kokoro jobs.
* Add a directory for Gas, including a readme, gitignore, and basic tools for test and clean.
* Update the repository CI to include tests in the Gas directory.

chore(gas): Core files for Gas

---

.kokoro/gas/trigger-protobuf.cfg
.kokoro/gas/trigger.sh
gas/.toys/gas/.test/test_kokoro_trigger.rb
gas/.toys/gas/kokoro-trigger.rb

This is the Trigger component for the Ruby Gems-As-a-Service mechanism. It implements a Kokoro job that can be invoked from a client CI/CD pipeline, receives the input, and orchestrates the builder and publisher.
Note: this PR may include more than one commit. If so, only the latest commit is unique to this PR; earlier commits are from earlier PRs that this PR is dependent on. Reviewers can restrict comments to the latest commit.
Includes the following:
* `gas/.toys/gas/kokoro-trigger.rb`: The `toys gas kokoro-trigger` implementation itself.
* `.kokoro/gas/trigger-protobuf.cfg`: Kokoro build configuration for Protobuf. In particular, includes default values for the list of platforms and ruby versions to build.
* `.kokoro/gas/trigger.sh`: Kokoro entrypoint (runs within the docker …

feat(gas): Implement protobuf kokoro trigger

---

gas/.toys/gas/.test/test_kokoro_trigger.rb
gas/.toys/gas/kokoro-trigger.rb

Support passing a directory for the `GAS_SOURCE_GEM` input to the Kokoro trigger. If a directory is passed, it must include, recursively, exactly one `*.gem` file whose `platform == "ruby"`.
Note: the `GAS_ADDITIONAL_GEMS` input already supported directories.
Also updated the test of the Kokoro trigger to exercise the directory usage because that's what we're going to expect from the Protobuf release process.

feat(gas): Support passing a directory to GAS_SOURCE_GEM

---

owlbot-postprocessor/lib/owlbot/common_modifiers.rb
owlbot-postprocessor/test/test_owlbot.rb

This hack is no longer necessary as the generator has been fixed upstream (https://github.com/googleapis/gapic-generator-ruby/pull/926)

fix(owlbot): Remove ruby-doc.org link hack

---

toys/release/.data/rad-yard-templates/default/layout/yaml/method.rb
toys/release/perform.rb
toys/release/please.rb

Fixes https://github.com/googleapis/doc-pipeline/issues/423
The issue, apparently, is that when a `@param` tag is _not_ annotated with a type, the `types` field is set to `nil`, which causes a crash here because we're calling `map` on the result. Generally, we always include a type for a `@param` tag, even if it's just `[Object]`, but it looks like one slipped through in https://github.com/googleapis/google-cloud-ruby/pull/21002/files (dataset.rb line 990). I'll fix that separately, but for docgen, we can make it robust against that case by calling `to_a` on the `types` to map `nil` to the empty array before calling `map` on it.
Also updates the release script so failures in build-rad cause a full abort of publish-rad rather than letting it attempt to publish an incomplete tarball.

fix(rad): Fix crash when a param doesn't specify a type

---

.kokoro/gas/trigger-protobuf.cfg

Ruby 2.6 has been dropped from protobuf's support window per https://cloud.google.com/ruby/getting-started/supported-ruby-versions?_ga=2.53600104.-1733366221.1688696481
This is needed for Ruby release for v24.0-rc1

chore: update trigger-protobuf.cfg to drop ruby 2.6 for protobuf

---

.kokoro/gas/trigger-cloud.cfg
.kokoro/gas/trigger-generic.cfg
.kokoro/gas/trigger-protobuf.cfg

fix(gas): Update default ruby versions in kokoro jobs to include 3.3

---

.kokoro/gas/trigger-cloud.cfg
.kokoro/gas/trigger-generic.cfg
.kokoro/gas/trigger-protobuf.cfg
gas/.toys/gas/.test/test_kokoro_trigger.rb
gas/.toys/gas/kokoro-trigger.rb
toys/release/perform.rb

Transitions the GAS kokoro jobs (notably the protobuf release job) to get their Rubygems keys from keystore instead of from GCS. This repurposes the existing `GAS_RUBYGEMS_KEY_FILE` environment variable to specify the keystore file path (relative to `KOKORO_KEYSTORE_DIR`) instead of a gfile-based path (relative to `KOKORO_GFILE_DIR`) so that we don't have to define a new environment variable through the entire Kokoro config system.
This should not be merged until the corresponding keystore key `rubygems-token-protobuf` has been pushed (internal cl/697837917) and made accessible to the jobs (internal cl/697841636).

fix(gas): Get rubygems key from keystore

---

toys/release/perform.rb

Removes the dependency on the releasetool publish-reporter for reporting release results back to the pull request, by reimplementing the logic in Ruby. Obtains the credentials from Secret Manager, exchanges with GitHub for an auth token, and makes the necessary GitHub calls to reproduce the reporting.
See also https://github.com/googleapis/testing-infra-docker/pull/423

chore(toys): Reimplement release reporter in Ruby

---

owlbot-postprocessor/Dockerfile
owlbot-postprocessor/lib/owlbot/multi_wrapper.rb

* Updated Ruby version and explicitly install a newer rexml to address internal task b/395172089
* Fixed an issue with multiwrapper readme generation where references were doubled.

fix(owlbot): Update Ruby version and fix repeated references in multiwrapper readmes

---

toys/gapic/linkinator.rb

StackOverflow recently has been returning 403 errors for Linkinator probes. This is a workaround for the common ruby link we use.

fix(toys-gapic): Workaround for stackoverflow denying linkinator requests

---

toys/README.md
toys/tombstone-library/.data/gemspec-template.erb
toys/tombstone-library/.data/license-template.erb
toys/tombstone-library/.data/readme-template.erb
toys/tombstone-library/.data/version-template.erb
toys/tombstone-library/.data/yardopts-template.erb
toys/tombstone-library/.toys.rb

Moved the logic from google-cloud-ruby's tombstone-gem tool, and reworked the workflow so it modifies an existing library (via pull request) instead of just publishing the tombstone directly.

feat(toys): Implement tombstone-library tool
